import type { ErrorCode } from './errors.type';

export const ERROR_CODE = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_EXISTS: 'ORDER_ALREADY_EXISTS',
  ILLEGAL_TRANSITION: 'ILLEGAL_TRANSITION',
  ORDER_ALREADY_DELIVERED: 'ORDER_ALREADY_DELIVERED',
  ORDER_NOT_RECOVERABLE: 'ORDER_NOT_RECOVERABLE',
  LEDGER_UNBALANCED: 'LEDGER_UNBALANCED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  ADMIN_DISABLED: 'ADMIN_DISABLED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export const ERROR_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = {
  VALIDATION_FAILED: 400,
  PRODUCT_NOT_FOUND: 404,
  PRODUCT_INACTIVE: 409,
  ORDER_NOT_FOUND: 404,
  ORDER_ALREADY_EXISTS: 409,
  ILLEGAL_TRANSITION: 409,
  ORDER_ALREADY_DELIVERED: 409,
  ORDER_NOT_RECOVERABLE: 409,
  LEDGER_UNBALANCED: 500,
  UNAUTHORIZED: 401,
  ADMIN_DISABLED: 403,
  INTERNAL_ERROR: 500,
  NOT_FOUND: 404,
};

export const INTERNAL_ERROR_MESSAGE = 'Внутренняя ошибка сервера';

export const ERROR_DEFAULT_MESSAGE: Readonly<Record<ErrorCode, string>> = {
  VALIDATION_FAILED: 'Некорректный запрос',
  PRODUCT_NOT_FOUND: 'Товар не найден',
  PRODUCT_INACTIVE: 'Товар недоступен',
  ORDER_NOT_FOUND: 'Заказ не найден',
  ORDER_ALREADY_EXISTS: 'Заказ уже существует',
  ILLEGAL_TRANSITION: 'Недопустимый переход статуса заказа',
  ORDER_ALREADY_DELIVERED: 'Заказ уже выдан',
  ORDER_NOT_RECOVERABLE: 'Заказ не подлежит восстановлению',
  LEDGER_UNBALANCED: 'Расхождение в бухгалтерской книге',
  UNAUTHORIZED: 'Не авторизовано',
  ADMIN_DISABLED: 'Административный интерфейс отключён',
  INTERNAL_ERROR: INTERNAL_ERROR_MESSAGE,
  NOT_FOUND: 'Ресурс не найден',
};

export const HTTP_STATUS_FALLBACK_CODE: Readonly<Record<number, ErrorCode>> = {
  400: ERROR_CODE.VALIDATION_FAILED,
  401: ERROR_CODE.UNAUTHORIZED,
  403: ERROR_CODE.UNAUTHORIZED,
  404: ERROR_CODE.NOT_FOUND,
};
